// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ban-screen/PermanentBan.tsx": () => import("../components/mockups/ban-screen/PermanentBan.tsx"),
  "./components/mockups/ban-screen/TempBan.tsx": () => import("../components/mockups/ban-screen/TempBan.tsx")
};
